### ISSUE TITLE
Mixing up similar named variable names

### ISSUE THREAD

**Issue by vicegold** [bongosway/insomnia-plugin-dotenv#3]
**Describe the bug**
When you have 2 similar named variables, the plugin always choses the first even when I selected the second.

**To Reproduce**
1. Create an ENV file that contains 2 keys:
- `RLG_PROD_PROTOCOL`
- `RLG_DEV_PROTOCOL`
2. Use this variable in your different environments

**Expected behavior**
I would expect that each environment would get the value of the env var I selected

**Screenshots**
![image](https://user-images.githubusercontent.com/3935131/106722697-8b6dd500-6606-11eb-875d-33f021529ee6.png)
![image](https://user-images.githubusercontent.com/3935131/106722770-a6d8e000-6606-11eb-8c28-f7c6f2f78846.png)

**Desktop (please complete the following information):**
 - OS: macOS 11.0.1
 - Insomnia 2020.5.2 / insomnia-plugin-dotenv 1.1.1

**Comment by bongosway** [comment]
Thanks @vicegold I checked your use case briefly and it seems to work as expected. Which is  each environment would get the value of the env var selected. 
I will do a screen recording once I am able.

**Comment by bongosway** [comment]
Hi @vicegold,
Please see a screen recording trying to reproduce your use case. kindly let me know if this solves the issue you had. Many thanks.

![2021-02-06 09 30 51](https://user-images.githubusercontent.com/7461869/107114936-55785d00-6861-11eb-9bf4-39677ff7efa7.gif)

**Comment by vicegold** [comment]
Sorry for the late reply. Can't reproduce it anymore now. I noticed that sometimes changes aren't used until I restart Insomnia so I think this issue was related to that.

**Comment by bongosway** [comment]
Thank you for your response. I will close the issue.
