### ISSUE TITLE
Switching between Sub Environments does not reload data

### ISSUE THREAD

**Issue by karloluis** [bongosway/insomnia-plugin-dotenv#4]
**Describe the bug**
When using environment variables to declare env file path per Sub Environment, switching sub environments won't reflect change in data. Also, hitting the refresh button won't reflect changes.

**To Reproduce**
1. Configure envFilePath in multiple Sub Environments
2. Make use of dotenv plugin with such variable
3. Change values in env file (bug)
4. Switch Sub Environment (bug)

Follow steps on GIF image in the Screenshot section as a reference

**Expected behavior**

Changing values on the .env files would be reflected in Insomnia dotenv variables.
Changing selected environments would reflect .env files values accordingly

**Screenshots**
![Bug Sub Environment](https://user-images.githubusercontent.com/4258614/109828278-c7637c80-7c3c-11eb-9a69-7222473b6de2.gif)

**Desktop (please complete the following information):**
 - OS: MAC OS - Big Sur
 - INSOMNIA VERSION: 
Version: Insomnia Core 2020.5.2
Release date: 09/12/2020
OS: Darwin x64 20.3.0
Electron: 9.1.1
Node: 12.14.1
V8: 8.3.110.13-electron.0
Architecture: x64
node-libcurl: libcurl/7.69.1 OpenSSL/1.1.1g zlib/1.2.11 brotli/1.0.7 libidn2/2.1.1 libssh2/1.9.0 nghttp2/1.41.0
 - Version 1.1.1

**Comment by bongosway** [comment]
@karloluis thanks for reporting this. I will take a look shortly

**Comment by weiannnnn** [comment]
Hi! I've been facing this issue as well. Has there been an update on the fix?

**Comment by bongosway** [comment]
I will do my utmost to look at this as soon as possible. Under heavy workload in day job. 

Where you can, please feel free to send in a PR. 

Much appreciated.

**Comment by bongosway** [comment]
@karloluis @weiannnnn 
v1.2.0 now released which fixes this issue. 
This commit  07c8aee contains the fix

Give it a spin please, feedback welcomed anytime.

Thanks for using this plugin.

**Comment by bongosway** [comment]
Closing this issue. Kindly reopen if you encounter the same issue.

Thank you so much.
