### ISSUE TITLE
dotenv Tag is Read as "Invalid Credentials" when used for Basic Auth

### ISSUE THREAD

**Issue by jmosley5** [bongosway/insomnia-plugin-dotenv#6]
**Describe the bug**
* Actual: When a user implements the dotenv tag in the Basic Auth Username and Password fields, the Username and Password is recognized as invalid even though they display correctly in the Live Preview

**To Reproduce**
1. Set up your .env file to have the variables USERNAME=username and PASSWORD=password
2. In Insomnia, set up your environment to include the following variable: "envFilePath": "~/repos/project/.env"
3. Set up the dotenv tag to accept the Username and Password in the Basic Auth Fields in Insomnia: Example - {% dotenv _.envFilePath, 'USERNAME' %} NOTE: The variable option is needed and not an upload of the .env file
4. Note the Preview. The preview of the Username loads successfully
5. Click Send
6. The call fails citing "Incorrect Credentials"
7. Remove the dotenv tag and load the credentials straight into the basic auth fields
8. Click Send 
9. The call is successful

**Expected behavior**
When a user implements the dotenv tag in the Basic Auth Username and Password fields, the Username and Password are recognized as valid credentials through Insomnia

**Screenshots**
Password displays correctly:
![image](https://user-images.githubusercontent.com/12145163/141380998-a6365309-4ae3-4eef-8b6d-82f1b7e06b23.png)

When run, the call fails:
![image](https://user-images.githubusercontent.com/12145163/141380704-7130060e-cf49-4d38-8cfd-7936d3ec7f97.png)
**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser No Browser used
 - Version of Insomnia-plugin-dotenv: 1.2.0

**Smartphone (please complete the following information):**
N/A

**Additional context**
NOTE: When I click the dotenv tag again, the variable option for the file is no longer selected and looks like it's returned to a loaded file state. I am not for sure if this is intended behavior.

**Comment by bongosway** [comment]
@jmosley5 Thank you for raising. Will be looked into as soon as possible.

**Comment by jmosley5** [comment]
> @jmosley5 Thank you for raising. Will be looked into as soon as possible.

Thank you!

**Comment by bongosway** [comment]
@jmosley5 I am not able to reproduce this error following your description.
Please see my steps below and let me know if I missed something:

Local.env file:
![41D65276-37AF-4391-A756-A134E0E0AD5C](https://user-images.githubusercontent.com/7461869/142176302-700f2df7-b7b5-4879-b274-1d9d2aeaa350.png)

Insonmia Environments Def:
![48EE01C4-1D9B-4F8A-B7CE-24D7203977C1](https://user-images.githubusercontent.com/7461869/142176508-5e6ce4ee-b8d3-4aa0-b8b6-13771a6e0d80.png)

dotenv tag:
![EEF2BFFD-B555-44B9-9942-19B2D2F4DEB5](https://user-images.githubusercontent.com/7461869/142176658-f2920497-fb54-450b-b35f-ea84a68b8b2f.png)
![C4EB1723-A621-4347-A724-4964FA77163F](https://user-images.githubusercontent.com/7461869/142176765-dda5b3e7-9294-4edd-b887-b63f651d8ce8.png)

Basic Auth setup with dotenv tags:
![178E3134-8635-4073-8535-8E346D347DE4](https://user-images.githubusercontent.com/7461869/142177074-9d00d508-8f2a-4d87-8bab-b44dd617c81c.png)

Request/Response successfull: ` https://postman-echo.com/basic-auth`
![4838B260-5508-4B3B-A105-65057CEFED3D](https://user-images.githubusercontent.com/7461869/142177198-4e3456cf-ff2c-43e8-a0ca-c4c5118cf7d6.png)

**Comment by jmosley5** [comment]
@bongosway, thank you for your feedback. 
One difference I do notice is that I have two variables in the environment that I'm working with. 

<img width="134" alt="Screen Shot 2021-11-17 at 4 12 53 PM" src="https://user-images.githubusercontent.com/12145163/142283447-696e78f0-310d-4272-8397-fcbcfad79022.png">

Can you add a second environment and see if that alters your results in any way?

Another test might be to add symbols in your password. How does it handle ^ or ! characters?

**Comment by bongosway** [comment]
@jmosley5 Tried the new use case still and it worked still. 

Used this password `2e#Fmb^5q%JZZWekL!`
Set base_url as well.

if you could create a minimum reproducible example as described here: https://stackoverflow.com/help/minimal-reproducible-example

it will help greatly.

Thank you so much!

**Comment by jmosley5** [comment]
@bongosway, thank you for your help. I'm going with a different solution entirely so you can close this. So sorry that we couldn't find a solution.
